apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
   name: bozobooks-dev
spec:
  destination:
    name: ''
    namespace: bozo-book-library-dev
    server: 'https://kubernetes.default.svc'
  source:
    path: dev/bozobooks-manifests
    repoURL: 'https://github.com/abvijaykumar/book-library-kube-infra'
    targetRevision: HEAD
    directory:
       recurse: true
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
